name: slack_notification
on:
  pull_request:
  issues:
    branches: [main, develop]

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: send Message to Slack Channel (general)
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: general
          slack-text: Event "${{ github.event_name }}" by ${{github.actor}}  in "${{ github.repository }}"