name: generate APK
on:
  push:
    branches: [feature/workflows]

jobs:
  generate-apk:
    runs-on: ubuntu-latest
    name: APK
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

#      - name: Generate Debug APK
#        run: ./gradlew clean assembleDevelopDebug
#
      - name : Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}./gradlew -q printVersionName)"
          id: android_version

#
#      - name: Get version
#        run: |
#          echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV

      - name: hessam
        run: ./gradlew -q printVersionName

      - name: print-result
        env:
          OUTCOME: ${{ steps.hessam.outcome }}
        run: |
          echo "$OUTCOME"

#      - name: Upload APK
#        uses: actions/upload-artifact@v1
#        with:
#          name: apk
#          path: app/build/outputs/apk/Develop/debug/Arashnia_debug_${{env.version_name}}_dev.apk