name: generate APK
on:
  push:
    branches: [feature/workflows]

jobs:
  generate-apk:
    runs-on: ubuntu-latest
    name: APK
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Generate Debug APK
        run: ./gradlew clean assembleDebug

      - name : Retrieve Develop Version
        id: developVersion
        run: |
          echo "::set-output name=VERSION_NAME_DEVELOP::$(${{github.workspace}}/gradlew -q printVersionNameDevelop)"

      - name: Get version Develop
        run: |
          echo "version_name_develop=${{steps.developVersion.outputs.VERSION_NAME_DEVELOP}}" >> $GITHUB_ENV

      - name: Retrieve Product Version
        id: ProductVersion
        run: |
            echo "::set-output name=VERSION_NAME_PRODUCT::$(${{github.workspace}}/gradlew -q printVersionNameProduct)"

      - name: Get version Product
        run: |
          echo "version_name_product=${{steps.ProductVersion.outputs.VERSION_NAME_PRODUCT}}" >> $GITHUB_ENV

      - name: Upload Develop APK to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          path: app/build/outputs/apk/Develop/debug/Arashnia_debug_${{env.version_name_develop}}_dev.apk
          channel: general
          title: develop version

      - name: Upload Product APK to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          path: app/build/outputs/apk/Product/debug/Arashnia_debug_${{env.version_name_product}}_pro.apk
          channel: general
          title: product version