name: upload file

on: [push]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: "11"
      - name: Create a file
        run: mkdir -p artifact
#        run: echo "HEsssam" > my_file.txt
#      - name: Accidentally upload to the same artifact via multiple jobs
#        uses: actions/upload-artifact@v3
#        with:
#          name: my-artifact
#          path: ${{ github.workspace }}